apiVersion: apps/v1
kind: Deployment
metadata:
  name: ran
  namespace: world
  labels:
    app: ran
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ran
  template:
    metadata:
      labels:
        app: ran
    spec:
      containers:
        - name: ran
          image: tdeslauriers/ran:latest
          ports:
            - containerPort: 8443
          env:
            - name: RAN_SERVICE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: cm-s2s-service
                  key: s2s-auth-client-id
            - name: RAN_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-s2s-service
                  key: s2s-auth-port
            - name: RAN_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-server-ca-prod
                  key: server-ca-cert
            - name: RAN_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-ran-server-cert
                  key: server-cert
            - name: RAN_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-ran-server-cert
                  key: server-key
            - name: RAN_DB_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-db-ca-prod
                  key: db-ca-cert
            - name: RAN_DB_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-ran-db-client-cert
                  key: client-cert
            - name: RAN_DB_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-ran-db-client-cert
                  key: client-key
            - name: RAN_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-s2s-db
                  key: db-url
            - name: RAN_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-s2s-db
                  key: db-name
            - name: RAN_DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-s2s-db
                  key: db-username
            - name: RAN_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-s2s-db
                  key: db-password
            - name: RAN_DATABASE_HMAC_INDEX_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-s2s-db
                  key: hmac-index-secret
            - name: RAN_FIELD_LEVEL_AES_GCM_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-s2s-db
                  key: aes-gcm-secret
            - name: RAN_S2S_JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-s2s-jwt-signing
                  key: jwt-signing-key
            - name: RAN_S2S_JWT_VERIFYING_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-s2s-jwt-signing
                  key: jwt-verifying-key
            - name: RAN_USER_JWT_VERIFYING_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-identity-jwt-signing
                  key: jwt-verifying-key
            - name: RAN_HMAC_S2S_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-s2s-cred-hmac
                  key: hmac-auth-pepper
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
