package register

import (
	"fmt"

	"github.com/tdeslauriers/carapace/pkg/validate"
)

// RegisterCmd is a model for a client registration request.
// Note: not a db model
type RegisterCmd struct {
	Id              string `json:"id,omitempty"`
	Name            string `json:"name"`
	Owner           string `json:"owner"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
	Emabled         bool   `json:"enabled"`
}

// ValidateCmd performs input validation check on client registration fields.
func (r *RegisterCmd) ValidateCmd() error {

	// Id is generated by the service, no validation needed

	// validate name
	if valid, err := validate.IsValidServiceName(r.Name); !valid {
		return fmt.Errorf("invalid service name: %v", err)
	}

	// validate owner
	if err := validate.IsValidName(r.Owner); err != nil {
		return fmt.Errorf("invalid service owner name: %v", err)
	}

	// validate password
	if err := validate.IsValidPassword(r.Password); err != nil {
		return fmt.Errorf("invalid password: %v", err)
	}

	// validate confirm password
	if r.Password != r.ConfirmPassword {
		return fmt.Errorf("password and confirm password values do not match")
	}

	// CreatedAt is a timestamp created programmatically, no validation needed
	// Slug is generated by the service, no validation needed
	// Enabled is a boolean, no validation needed
	// AccountExpired is a boolean, no validation needed
	// AccountLocked is a boolean, no validation needed

	return nil
}
